# RAG Eval — Шаг 1: Генерация тестового датасета Q&A

Для каждой заметки из `notes_dataset_v1.xlsx`:
1. Генерируем вопрос + эталонный ответ через `openai/gpt-5.1` (смарт-модель как оракул).
2. Определяем эталонный набор zettel-ов (ground truth) для метрик retrieval:
   через cosine-similarity эмбеддингов zettel-ов с текстом заметки.
3. Сохраняем в `synthetic_datasets/rag_qa_dataset.xlsx`.

**User в Neo4j:** `linker_eval_gpt-5.2`  
**Источник zettel-ов:** `synthetic_datasets/linker/reference_linker_gpt-5.2.xlsx`

In [1]:
import os
import sys
import uuid
import json
import ast
import time
import logging
from pathlib import Path
from datetime import datetime
from threading import Lock
from concurrent.futures import ThreadPoolExecutor, as_completed
from collections import defaultdict

import numpy as np
import pandas as pd
from tqdm import tqdm
from pydantic import BaseModel, Field
from langchain_openai import ChatOpenAI
from langchain_core.messages import HumanMessage, SystemMessage
from dotenv import load_dotenv

PROJECT_ROOT = Path.cwd().parent
sys.path.insert(0, str(PROJECT_ROOT))
load_dotenv(PROJECT_ROOT / '.env')

from zettelkasten.linker import LocalEmbeddingModel

logging.basicConfig(level=logging.INFO, format='%(asctime)s | %(levelname)s | %(message)s')
logger = logging.getLogger(__name__)
print('✅ imports ok')

/Users/nastya/github/Executive_Exocortex/.venv/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

✅ imports ok

In [2]:
GENERATION_MODEL      = 'openai/gpt-5.1'
EVAL_USER_ID          = 'linker_eval_gpt-5.2'
MAX_WORKERS           = 15
GT_SIM_THRESHOLD      = 0.60    # порог similarity для zettel → note mapping

NOTES_PATH    = Path('synthetic_datasets/notes_dataset_v1.xlsx')
LINKER_PATH   = Path('synthetic_datasets/linker/reference_linker_gpt-5.2.xlsx')
OUTPUT_PATH   = Path('synthetic_datasets/rag_qa_dataset.xlsx')

OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
print(f'Paths configured. GT threshold: {GT_SIM_THRESHOLD}')

Paths configured. GT threshold: 0.6

In [3]:
df_notes  = pd.read_excel(NOTES_PATH)
df_linker = pd.read_excel(LINKER_PATH)

# фильтруем только карточки нашего пользователя
if 'user_id' in df_linker.columns:
    df_linker = df_linker[df_linker['user_id'] == EVAL_USER_ID].reset_index(drop=True)

print(f'Notes: {len(df_notes)} rows')
print(f'Linker zettels: {len(df_linker)} rows')
print(f'Linker cols: {list(df_linker.columns)}')
df_notes.head(3)

Notes: 200 rows
Linker zettels: 484 rows
Linker cols: ['Unnamed: 0', 'zettel_id', 'luhmann_id', 'content', 'thought_type', 'tags', 'is_root_topic', 'user_id', 'embedding', 'created_at', 'updated_at', 'similarity', 'action', 'reasoning', 'candidates_found', 'target_zettel_id']

,№,note_id,note_text,num_sentences,actual_sentences,domain,style,created_at
0,1,c09941ef-4576-4710-936d-dc12911f0ab7,Думаю по реструктуризации после разговора с Ма...,4,4,реструктуризация компании,рабочие мысли,2026-06-27 11:49:56
1,2,1d4f8aa3-9dc0-4898-b324-3b3c61a67436,Разобрал цифры по благотворительному проекту С...,3,3,благотворительный проект,анализ ситуации,2026-06-27 11:49:56
2,3,3a046e1a-56fb-4abb-afc4-cb65d85d3a24,Звонок с клиентом Северсталь Диджитал по проек...,6,6,работа с клиентами,записи после звонка,2026-06-27 11:49:58

In [4]:
embedder = LocalEmbeddingModel()

print('Embedding notes...')
note_texts = df_notes['note_text'].tolist()
note_embs  = np.array([embedder.embed_passage(t) for t in tqdm(note_texts, desc='notes')])
print(f'Note embeddings shape: {note_embs.shape}')

2026-06-28 17:12:55,916 | INFO | HTTP Request: HEAD https://huggingface.co/intfloat/multilingual-e5-base/resolve/main/modules.json "HTTP/1.1 307 Temporary Redirect"
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
2026-06-28 17:12:55,917 | WARNING | Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
2026-06-28 17:12:56,009 | INFO | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/intfloat/multilingual-e5-base/d128750597153bb5987e10b1c3493a34e5a4502a/modules.json "HTTP/1.1 200 OK"
2026-06-28 17:12:56,203 | INFO | HTTP Request: HEAD https://huggingface.co/intfloat/multilingual-e5-base/resolve/main/config_sentence_transformers.json "HTTP/1.1 404 Not Found"
2026-06-28 17:12:56,204 | INFO | Loading SentenceTransformer model from intfloat/multilingual-e5-base.
2026-06-28 17:12:56,420 | INFO | HTTP Request: HEAD https://huggingface.co/intfloat/multilingual-e5-base/resolve/main/config_sentence_transformers.json "HTTP/1.1 404 Not Found"
2026-06-28 17:12:56,625 | INFO | HTTP Request: HEAD https://huggingface.co/intfloat/multilingual-e5-base/resolve/main/README.md "HTTP/1.1 307 Temporary Redirect"
2026-06-28 17:12:56,713 | INFO | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/intfloat/multilingual-e5-base/d128750597153bb5987e10b1c3493a34e5a4502a/README.md "HTTP/1.1 200 OK"
2026-06-28 17:12:56,913 | INFO | HTTP Request: HEAD https://huggingface.co/intfloat/multilingual-e5-base/resolve/main/modules.json "HTTP/1.1 307 Temporary Redirect"
2026-06-28 17:12:57,011 | INFO | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/intfloat/multilingual-e5-base/d128750597153bb5987e10b1c3493a34e5a4502a/modules.json "HTTP/1.1 200 OK"
2026-06-28 17:12:57,196 | INFO | HTTP Request: HEAD https://huggingface.co/intfloat/multilingual-e5-base/resolve/main/sentence_bert_config.json "HTTP/1.1 307 Temporary Redirect"
2026-06-28 17:12:57,307 | INFO | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/intfloat/multilingual-e5-base/d128750597153bb5987e10b1c3493a34e5a4502a/sentence_bert_config.json "HTTP/1.1 200 OK"
2026-06-28 17:12:57,482 | INFO | HTTP Request: HEAD https://huggingface.co/intfloat/multilingual-e5-base/resolve/main/adapter_config.json "HTTP/1.1 404 Not Found"
2026-06-28 17:12:57,682 | INFO | HTTP Request: HEAD https://huggingface.co/intfloat/multilingual-e5-base/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-06-28 17:12:57,777 | INFO | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/intfloat/multilingual-e5-base/d128750597153bb5987e10b1c3493a34e5a4502a/config.json "HTTP/1.1 200 OK"
Loading weights: 100%|██████████| 199/199 [00:00<00:00, 10499.61it/s]
2026-06-28 17:12:58,062 | INFO | HTTP Request: HEAD https://huggingface.co/intfloat/multilingual-e5-base/resolve/main/processor_config.json "HTTP/1.1 404 Not Found"
2026-06-28 17:12:58,233 | INFO | HTTP Request: HEAD https://huggingface.co/intfloat/multilingual-e5-base/resolve/main/preprocessor_config.json "HTTP/1.1 404 Not Found"
2026-06-28 17:12:58,444 | INFO | HTTP Request: HEAD https://huggingface.co/intfloat/multilingual-e5-base/resolve/main/video_preprocessor_config.json "HTTP/1.1 404 Not Found"
2026-06-28 17:12:58,631 | INFO | HTTP Request: HEAD https://huggingface.co/intfloat/multilingual-e5-base/resolve/main/preprocessor_config.json "HTTP/1.1 404 Not Found"
2026-06-28 17:12:58,795 | INFO | HTTP Request: HEAD https://huggingface.co/intfloat/multilingual-e5-base/resolve/main/tokenizer_config.json "HTTP/1.1 307 Temporary Redirect"
2026-06-28 17:12:58,891 | INFO | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/intfloat/multilingual-e5-base/d128750597153bb5987e10b1c3493a34e5a4502a/tokenizer_config.json "HTTP/1.1 200 OK"
2026-06-28 17:12:59,092 | INFO | HTTP Request: HEAD https://huggingface.co/intfloat/multilingual-e5-base/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-06-28 17:12:59,188 | INFO | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/intfloat/multilingual-e5-base/d128750597153bb5987e10b1c3493a34e5a4502a/config.json "HTTP/1.1 200 OK"
2026-06-28 17:12:59,369 | INFO | HTTP Request: HEAD https://huggingface.co/intfloat/multilingual-e5-base/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-06-28 17:12:59,457 | INFO | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/intfloat/multilingual-e5-base/d128750597153bb5987e10b1c3493a34e5a4502a/config.json "HTTP/1.1 200 OK"
2026-06-28 17:12:59,653 | INFO | HTTP Request: HEAD https://huggingface.co/intfloat/multilingual-e5-base/resolve/main/tokenizer_config.json "HTTP/1.1 307 Temporary Redirect"
2026-06-28 17:12:59,755 | INFO | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/intfloat/multilingual-e5-base/d128750597153bb5987e10b1c3493a34e5a4502a/tokenizer_config.json "HTTP/1.1 200 OK"
2026-06-28 17:12:59,974 | INFO | HTTP Request: GET https://huggingface.co/api/models/intfloat/multilingual-e5-base/tree/main/additional_chat_templates?recursive=false&expand=false "HTTP/1.1 404 Not Found"
2026-06-28 17:13:00,169 | INFO | HTTP Request: GET https://huggingface.co/api/models/intfloat/multilingual-e5-base/tree/main?recursive=true&expand=false "HTTP/1.1 200 OK"
2026-06-28 17:13:01,480 | INFO | HTTP Request: GET https://huggingface.co/api/models/intfloat/multilingual-e5-base "HTTP/1.1 200 OK"
2026-06-28 17:13:01,854 | INFO | HTTP Request: HEAD https://huggingface.co/intfloat/multilingual-e5-base/resolve/main/1_Pooling/config.json "HTTP/1.1 307 Temporary Redirect"
2026-06-28 17:13:01,963 | INFO | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/intfloat/multilingual-e5-base/d128750597153bb5987e10b1c3493a34e5a4502a/1_Pooling%2Fconfig.json "HTTP/1.1 200 OK"
2026-06-28 17:13:02,175 | INFO | HTTP Request: GET https://huggingface.co/api/models/intfloat/multilingual-e5-base "HTTP/1.1 200 OK"
/Users/nastya/github/Executive_Exocortex/zettelkasten/linker.py:84: FutureWarning: The `get_sentence_embedding_dimension` method has been renamed to `get_embedding_dimension`.
  return self.model.get_sentence_embedding_dimension()

[EmbeddingModel] intfloat/multilingual-e5-base загружена за 7.7с (dim=768, device=mps)
Embedding notes...

notes: 100%|██████████| 200/200 [00:10<00:00, 18.46it/s]

Note embeddings shape: (200, 768)

In [5]:
def parse_embedding(val):
    """Парсим embedding из строки / списка / None."""
    if val is None or (isinstance(val, float) and np.isnan(val)):
        return None
    if isinstance(val, list):
        return np.array(val, dtype=np.float32)
    if isinstance(val, str):
        try:
            return np.array(ast.literal_eval(val), dtype=np.float32)
        except Exception:
            return None
    return None

raw_embs = [parse_embedding(e) for e in df_linker['embedding']]
valid_mask = [e is not None for e in raw_embs]
df_linker = df_linker[valid_mask].reset_index(drop=True)
zettel_embs = np.array([e for e in raw_embs if e is not None])

# Нормализуем zettel embeddings (на случай если они не нормализованы)
norms = np.linalg.norm(zettel_embs, axis=1, keepdims=True)
zettel_embs = zettel_embs / (norms + 1e-10)

print(f'Zettel embeddings shape: {zettel_embs.shape}')
print(f'Filtered zettels with valid embeddings: {len(df_linker)}')

Zettel embeddings shape: (484, 768)
Filtered zettels with valid embeddings: 484

In [6]:
# Матрица сходства: (n_zettels x n_notes)
sim_matrix = zettel_embs @ note_embs.T
print(f'Similarity matrix shape: {sim_matrix.shape}')

# Для каждого zettel → best matching note
best_note_idx = sim_matrix.argmax(axis=1)
best_note_sim = sim_matrix.max(axis=1)

df_linker['matched_note_id']  = None
df_linker['matched_note_sim'] = best_note_sim

for i in range(len(df_linker)):
    if best_note_sim[i] >= GT_SIM_THRESHOLD:
        df_linker.at[i, 'matched_note_id'] = df_notes.iloc[best_note_idx[i]]['note_id']

matched = df_linker['matched_note_id'].notna().sum()
print(f'Zettels matched to notes (sim >= {GT_SIM_THRESHOLD}): {matched} / {len(df_linker)}')

# note_id → список zettel_ids (ground truth для retrieval)
note_to_gt_zettels = defaultdict(list)
for _, row in df_linker.iterrows():
    if row['matched_note_id'] is not None:
        note_to_gt_zettels[row['matched_note_id']].append(row['zettel_id'])

unique_notes_with_gt = len(note_to_gt_zettels)
print(f'Notes with at least 1 matched zettel: {unique_notes_with_gt}')
print(f'Avg GT zettels per note: {np.mean([len(v) for v in note_to_gt_zettels.values()]):.1f}')

Similarity matrix shape: (484, 200)
Zettels matched to notes (sim >= 0.6): 484 / 484
Notes with at least 1 matched zettel: 131
Avg GT zettels per note: 3.7

In [7]:
QA_SYSTEM_PROMPT = """Ты — топ-менеджер, который пользуется персональной системой управления знаниями.
Тебе показывают одну из твоих старых заметок.

Твоя задача — придумать ОДИН реалистичный вопрос, который ты мог бы задать системе СПУСТЯ НЕКОТОРОЕ ВРЕМЯ
после того, как сделал эту заметку. Вопрос должен:
- Звучать как натуральный вопрос к своей базе знаний («напомни», «что мы решали», «кто отвечал», «какие цифры» и т.д.)
- Быть специфичным для данной заметки (содержать уникальные детали: имена, проекты, цифры)
- Иметь однозначный ответ в тексте заметки
- Не быть слишком простым («о чём эта заметка?») и не слишком широким

Также предоставь:
- reference_answer: точный и полный ответ на вопрос, основанный ТОЛЬКО на тексте заметки
- question_type: тип вопроса (factual / summary / action_items / risk / decision / detail)
- key_concepts: список 3-7 ключевых концептов из заметки, которые должны присутствовать в ответе"""


class QAPair(BaseModel):
    question: str = Field(description="Натуральный вопрос топ-менеджера к своей базе знаний")
    reference_answer: str = Field(description="Полный эталонный ответ на основе заметки")
    question_type: str = Field(description="Тип: factual / summary / action_items / risk / decision / detail")
    key_concepts: list[str] = Field(description="3-7 ключевых концептов для оценки покрытия ответа")


print('QA prompt schema ready')

QA prompt schema ready

In [8]:
save_lock = Lock()
results   = []


def generate_single_qa(row: dict) -> dict | None:
    note_id   = row['note_id']
    note_text = row['note_text']
    domain    = row.get('domain', '')
    style     = row.get('style', '')

    llm = ChatOpenAI(
        model=GENERATION_MODEL,
        temperature=0.7,
        api_key=os.getenv('LLM_API_KEY'),
        base_url=os.getenv('LLM_BASE_URL'),
    )

    try:
        qa: QAPair = llm.with_structured_output(QAPair).invoke([
            SystemMessage(content=QA_SYSTEM_PROMPT),
            HumanMessage(content=f"Заметка:\n{note_text}"),
        ])
        return {
            'question_id':             f'Q-{uuid.uuid4().hex[:8].upper()}',
            'source_note_id':          note_id,
            'note_text':               note_text,
            'note_domain':             domain,
            'note_style':              style,
            'question':                qa.question,
            'reference_answer':        qa.reference_answer,
            'question_type':           qa.question_type,
            'key_concepts':            json.dumps(qa.key_concepts, ensure_ascii=False),
            'ground_truth_zettel_ids': json.dumps(
                note_to_gt_zettels.get(note_id, []), ensure_ascii=False
            ),
            'n_gt_zettels':            len(note_to_gt_zettels.get(note_id, [])),
            'generated_at':            datetime.now().isoformat(),
            'model_name':              GENERATION_MODEL,
        }
    except Exception as e:
        logger.error(f'Error generating QA for note {note_id}: {e}')
        return None


rows = df_notes.to_dict('records')

with ThreadPoolExecutor(max_workers=MAX_WORKERS) as executor:
    futures = {executor.submit(generate_single_qa, r): r['note_id'] for r in rows}
    for future in tqdm(as_completed(futures), total=len(futures), desc='Generating Q&A'):
        res = future.result()
        if res is not None:
            with save_lock:
                results.append(res)

df_qa = pd.DataFrame(results)
df_qa['№'] = range(1, len(df_qa) + 1)
print(f'Generated: {len(df_qa)} Q&A pairs')
df_qa.head(3)

Generating Q&A:   0%|          | 0/200 [00:00<?, ?it/s]2026-06-28 17:13:16,608 | INFO | HTTP Request: POST https://litellm.tokengate.ru/v1/chat/completions "HTTP/1.1 503 Service Unavailable"
2026-06-28 17:13:16,610 | INFO | Retrying request to /chat/completions in 0.421826 seconds
2026-06-28 17:13:16,619 | INFO | HTTP Request: POST https://litellm.tokengate.ru/v1/chat/completions "HTTP/1.1 503 Service Unavailable"
2026-06-28 17:13:16,620 | INFO | Retrying request to /chat/completions in 0.464909 seconds
2026-06-28 17:13:17,205 | INFO | HTTP Request: POST https://litellm.tokengate.ru/v1/chat/completions "HTTP/1.1 429 Too Many Requests"
2026-06-28 17:13:17,205 | INFO | Retrying request to /chat/completions in 0.840266 seconds
2026-06-28 17:13:17,372 | INFO | HTTP Request: POST https://litellm.tokengate.ru/v1/chat/completions "HTTP/1.1 503 Service Unavailable"
2026-06-28 17:13:17,373 | INFO | Retrying request to /chat/completions in 0.909840 seconds
2026-06-28 17:13:18,281 | INFO | HTTP Request: POST https://litellm.tokengate.ru/v1/chat/completions "HTTP/1.1 200 OK"
Generating Q&A:   0%|          | 1/200 [00:03<13:05,  3.95s/it]2026-06-28 17:13:18,297 | INFO | HTTP Request: POST https://litellm.tokengate.ru/v1/chat/completions "HTTP/1.1 200 OK"
2026-06-28 17:13:18,443 | INFO | HTTP Request: POST https://litellm.tokengate.ru/v1/chat/completions "HTTP/1.1 200 OK"
2026-06-28 17:13:18,444 | INFO | HTTP Request: POST https://litellm.tokengate.ru/v1/chat/completions "HTTP/1.1 200 OK"
Generating Q&A:   2%|▏         | 3/200 [00:04<03:33,  1.08s/it]2026-06-28 17:13:18,484 | INFO | HTTP Request: POST https://litellm.tokengate.ru/v1/chat/completions "HTTP/1.1 200 OK"
2026-06-28 17:13:18,494 | INFO | HTTP Request: POST https://litellm.tokengate.ru/v1/chat/completions "HTTP/1.1 200 OK"
2026-06-28 17:13:18,517 | INFO | HTTP Request: POST https://litellm.tokengate.ru/v1/chat/completions "HTTP/1.1 200 OK"
2026-06-28 17:13:18,953 | INFO | HTTP Request: POST https://litellm.tokengate.ru/v1/chat/completions "HTTP/1.1 429 Too Many Requests"
2026-06-28 17:13:18,955 | INFO | Retrying request to /chat/completions in 0.415304 seconds
2026-06-28 17:13:18,959 | INFO | HTTP Request: POST https://litellm.tokengate.ru/v1/chat/completions "HTTP/1.1 429 Too Many Requests"
2026-06-28 17:13:18,960 | INFO | Retrying request to /chat/completions in 0.495262 seconds
2026-06-28 17:13:18,964 | INFO | HTTP Request: POST https://litellm.tokengate.ru/v1/chat/completions "HTTP/1.1 429 Too Many Requests"
2026-06-28 17:13:18,965 | INFO | Retrying request to /chat/completions in 0.405657 seconds
2026-06-28 17:13:19,208 | INFO | HTTP Request: POST https://litellm.tokengate.ru/v1/chat/completions "HTTP/1.1 200 OK"
Generating Q&A:   4%|▍         | 8/200 [00:04<01:18,  2.45it/s]2026-06-28 17:13:19,524 | INFO | HTTP Request: POST https://litellm.tokengate.ru/v1/chat/completions "HTTP/1.1 200 OK"
Generating Q&A:   4%|▍         | 9/200 [00:05<01:14,  2.55it/s]2026-06-28 17:13:20,095 | INFO | HTTP Request: POST https://litellm.tokengate.ru/v1/chat/completions "HTTP/1.1 200 OK"
Generating Q&A:   5%|▌         | 10/200 [00:05<01:21,  2.34it/s]2026-06-28 17:13:20,137 | INFO | HTTP Request: POST https://litellm.tokengate.ru/v1/chat/completions "HTTP/1.1 200 OK"
2026-06-28 17:13:20,650 | INFO | HTTP Request: POST https://litellm.tokengate.ru/v1/chat/completions "HTTP/1.1 200 OK"
Generating Q&A:   6%|▌         | 12/200 [00:06<01:10,  2.68it/s]2026-06-28 17:13:20,669 | INFO | HTTP Request: POST https://litellm.tokengate.ru/v1/chat/completions "HTTP/1.1 200 OK"
2026-06-28 17:13:20,705 | INFO | HTTP Request: POST https://litellm.tokengate.ru/v1/chat/completions "HTTP/1.1 503 Service Unavailable"
2026-06-28 17:13:20,706 | INFO | Retrying request to /chat/completions in 0.434535 seconds
2026-06-28 17:13:20,885 | INFO | HTTP Request: POST https://litellm.tokengate.ru/v1/chat/completions "HTTP/1.1 200 OK"
Generating Q&A:   7%|▋         | 14/200 [00:06<00:53,  3.48it/s]2026-06-28 17:13:20,952 | INFO | HTTP Request: POST https://litellm.tokengate.ru/v1/chat/completions "HTTP/1.1 200 OK"
2026-06-28 17:13:21,192 | INFO | HTTP Request: POST https://litellm.tokengate.ru/v1/chat/completions "HTTP/1.1 200 OK"
Generating Q&A:   8%|▊         | 16/200 [00:06<00:44,  4.12it/s]2026-06-28 17:13:21,905 | INFO | HTTP Request: POST https://litellm.tokengate.ru/v1/chat/completions "HTTP/1.1 200 OK"
Generating Q&A:   8%|▊         | 17/200 [00:07<01:00,  3.02it/s]2026-06-28 17:13:22,036 | INFO | HTTP Request: POST https://litellm.tokengate.ru/v1/chat/completions "HTTP/1.1 200 OK"
Generating Q&A:   9%|▉         | 18/200 [00:07<00:52,  3.46it/s]2026-06-28 17:13:22,198 | INFO | HTTP Request: POST https://litellm.tokengate.ru/v1/chat/completions "HTTP/1.1 200 OK"
Generating Q&A:  10%|▉         | 19/200 [00:07<00:47,  3.85it/s]2026-06-28 17:13:22,337 | INFO | HTTP Request: POST https://litellm.tokengate.ru/v1/chat/completions "HTTP/1.1 200 OK"
Generating Q&A:  10%|█         | 20/200 [00:07<00:41,  4.37it/s]2026-06-28 17:13:22,368 | INFO | HTTP Request: POST https://litellm.tokengate.ru/v1/chat/completions "HTTP/1.1 429 Too Many Requests"
2026-06-28 17:13:22,369 | INFO | Retrying request to /chat/completions in 0.493378 seconds
2026-06-28 17:13:22,459 | INFO | HTTP Request: POST https://litellm.tokengate.ru/v1/chat/completions "HTTP/1.1 200 OK"
Generating Q&A:  10%|█         | 21/200 [00:08<00:35,  4.98it/s]2026-06-28 17:13:22,628 | INFO | HTTP Request: POST https://litellm.tokengate.ru/v1/chat/completions "HTTP/1.1 200 OK"
Generating Q&A:  11%|█         | 22/200 [00:08<00:34,  5.20it/s]2026-06-28 17:13:22,805 | INFO | HTTP Request: POST https://litellm.tokengate.ru/v1/chat/completions "HTTP/1.1 429 Too Many Requests"
2026-06-28 17:13:22,806 | INFO | Retrying request to /chat/completions in 0.395765 seconds
2026-06-28 17:13:23,014 | INFO | HTTP Request: POST https://litellm.tokengate.ru/v1/chat/completions "HTTP/1.1 200 OK"
Generating Q&A:  12%|█▏        | 23/200 [00:08<00:43,  4.05it/s]2026-06-28 17:13:23,056 | INFO | HTTP Request: POST https://litellm.tokengate.ru/v1/chat/completions "HTTP/1.1 200 OK"
2026-06-28 17:13:23,233 | INFO | HTTP Request: POST https://litellm.tokengate.ru/v1/chat/completions "HTTP/1.1 429 Too Many Requests"
2026-06-28 17:13:23,234 | INFO | Retrying request to /chat/completions in 0.441320 seconds
2026-06-28 17:13:23,324 | INFO | HTTP Request: POST https://litellm.tokengate.ru/v1/chat/completions "HTTP/1.1 200 OK"
Generating Q&A:  12%|█▎        | 25/200 [00:08<00:36,  4.86it/s]2026-06-28 17:13:23,543 | INFO | HTTP Request: POST https://litellm.tokengate.ru/v1/chat/completions "HTTP/1.1 200 OK"
Generating Q&A:  13%|█▎        | 26/200 [00:09<00:36,  4.79it/s]2026-06-28 17:13:23,784 | INFO | HTTP Request: POST https://litellm.tokengate.ru/v1/chat/completions "HTTP/1.1 200 OK"
Generating Q&A:  14%|█▎        | 27/200 [00:09<00:37,  4.61it/s]2026-06-28 17:13:23,853 | INFO | HTTP Request: POST https://litellm.tokengate.ru/v1/chat/completions "HTTP/1.1 429 Too Many Requests"
2026-06-28 17:13:23,853 | INFO | Retrying request to /chat/completions in 0.867293 seconds
2026-06-28 17:13:24,015 | INFO | HTTP Request: POST https://litellm.tokengate.ru/v1/chat/completions "HTTP/1.1 200 OK"
Generating Q&A:  14%|█▍        | 28/200 [00:09<00:38,  4.53it/s]2026-06-28 17:13:24,307 | INFO | HTTP Request: POST https://litellm.tokengate.ru/v1/chat/completions "HTTP/1.1 200 OK"
Generating Q&A:  14%|█▍        | 29/200 [00:09<00:41,  4.15it/s]2026-06-28 17:13:24,476 | INFO | HTTP Request: POST https://litellm.tokengate.ru/v1/chat/completions "HTTP/1.1 429 Too Many Requests"
2026-06-28 17:13:24,477 | INFO | Retrying request to /chat/completions in 0.415432 seconds
2026-06-28 17:13:24,630 | INFO | HTTP Request: POST https://litellm.tokengate.ru/v1/chat/completions "HTTP/1.1 200 OK"
Generating Q&A:  15%|█▌        | 30/200 [00:10<00:44,  3.78it/s]2026-06-28 17:13:24,822 | INFO | HTTP Request: POST https://litellm.tokengate.ru/v1/chat/completions "HTTP/1.1 429 Too Many Requests"
2026-06-28 17:13:24,823 | INFO | Retrying request to /chat/completions in 0.375260 seconds
2026-06-28 17:13:24,836 | INFO | HTTP Request: POST https://litellm.tokengate.ru/v1/chat/completions "HTTP/1.1 200 OK"
Generating Q&A:  16%|█▌        | 31/200 [00:10<00:41,  4.04it/s]2026-06-28 17:13:24,906 | INFO | HTTP Request: POST https://litellm.tokengate.ru/v1/chat/completions "HTTP/1.1 200 OK"
2026-06-28 17:13:25,076 | INFO | HTTP Request: POST https://litellm.tokengate.ru/v1/chat/completions "HTTP/1.1 429 Too Many Requests"
2026-06-28 17:13:25,077 | INFO | Retrying request to /chat/completions in 0.406397 seconds
2026-06-28 17:13:25,190 | INFO | HTTP Request: POST https://litellm.tokengate.ru/v1/chat/completions "HTTP/1.1 200 OK"
Generating Q&A:  16%|█▋        | 33/200 [00:10<00:36,  4.64it/s]2026-06-28 17:13:25,423 | INFO | HTTP Request: POST https://litellm.tokengate.ru/v1/chat/completions "HTTP/1.1 429 Too Many Requests"
2026-06-28 17:13:25,424 | INFO | Retrying request to /chat/completions in 0.415373 seconds
2026-06-28 17:13:25,425 | INFO | HTTP Request: POST https://litellm.tokengate.ru/v1/chat/completions "HTTP/1.1 200 OK"
Generating Q&A:  17%|█▋        | 34/200 [00:11<00:36,  4.54it/s]2026-06-28 17:13:25,443 | INFO | HTTP Request: POST https://litellm.tokengate.ru/v1/chat/completions "HTTP/1.1 429 Too Many Requests"
2026-06-28 17:13:25,444 | INFO | Retrying request to /chat/completions in 0.986791 seconds
2026-06-28 17:13:25,856 | INFO | HTTP Request: POST https://litellm.tokengate.ru/v1/chat/completions "HTTP/1.1 200 OK"
Generating Q&A:  18%|█▊        | 35/200 [00:11<00:45,  3.64it/s]2026-06-28 17:13:25,962 | INFO | HTTP Request: POST https://litellm.tokengate.ru/v1/chat/completions "HTTP/1.1 200 OK"
Generating Q&A:  18%|█▊        | 36/200 [00:11<00:37,  4.37it/s]2026-06-28 17:13:26,424 | INFO | HTTP Request: POST https://litellm.tokengate.ru/v1/chat/completions "HTTP/1.1 200 OK"
Generating Q&A:  18%|█▊        | 37/200 [00:12<00:47,  3.40it/s]2026-06-28 17:13:26,581 | INFO | HTTP Request: POST https://litellm.tokengate.ru/v1/chat/completions "HTTP/1.1 200 OK"
Generating Q&A:  19%|█▉        | 38/200 [00:12<00:41,  3.92it/s]2026-06-28 17:13:26,760 | INFO | HTTP Request: POST https://litellm.tokengate.ru/v1/chat/completions "HTTP/1.1 429 Too Many Requests"
2026-06-28 17:13:26,762 | INFO | Retrying request to /chat/completions in 0.392687 seconds
2026-06-28 17:13:26,934 | INFO | HTTP Request: POST https://litellm.tokengate.ru/v1/chat/completions "HTTP/1.1 200 OK"
Generating Q&A:  20%|█▉        | 39/200 [00:12<00:45,  3.53it/s]2026-06-28 17:13:26,938 | INFO | HTTP Request: POST https://litellm.tokengate.ru/v1/chat/completions "HTTP/1.1 200 OK"
2026-06-28 17:13:27,314 | INFO | HTTP Request: POST https://litellm.tokengate.ru/v1/chat/completions "HTTP/1.1 200 OK"
Generating Q&A:  20%|██        | 41/200 [00:12<00:38,  4.15it/s]2026-06-28 17:13:27,321 | INFO | HTTP Request: POST https://litellm.tokengate.ru/v1/chat/completions "HTTP/1.1 200 OK"
2026-06-28 17:13:27,691 | INFO | HTTP Request: POST https://litellm.tokengate.ru/v1/chat/completions "HTTP/1.1 200 OK"
Generating Q&A:  22%|██▏       | 43/200 [00:13<00:34,  4.53it/s]2026-06-28 17:13:27,737 | INFO | HTTP Request: POST https://litellm.tokengate.ru/v1/chat/completions "HTTP/1.1 200 OK"
2026-06-28 17:13:28,387 | INFO | HTTP Request: POST https://litellm.tokengate.ru/v1/chat/completions "HTTP/1.1 200 OK"
Generating Q&A:  22%|██▎       | 45/200 [00:14<00:41,  3.75it/s]2026-06-28 17:13:28,477 | INFO | HTTP Request: POST https://litellm.tokengate.ru/v1/chat/completions "HTTP/1.1 200 OK"
2026-06-28 17:13:28,699 | INFO | HTTP Request: POST https://litellm.tokengate.ru/v1/chat/completions "HTTP/1.1 200 OK"
Generating Q&A:  24%|██▎       | 47/200 [00:14<00:35,  4.37it/s]2026-06-28 17:13:28,902 | INFO | HTTP Request: POST https://litellm.tokengate.ru/v1/chat/completions "HTTP/1.1 200 OK"
Generating Q&A:  24%|██▍       | 48/200 [00:14<00:34,  4.46it/s]2026-06-28 17:13:29,113 | INFO | HTTP Request: POST https://litellm.tokengate.ru/v1/chat/completions "HTTP/1.1 200 OK"
Generating Q&A:  24%|██▍       | 49/200 [00:14<00:33,  4.53it/s]2026-06-28 17:13:29,133 | INFO | HTTP Request: POST https://litellm.tokengate.ru/v1/chat/completions "HTTP/1.1 200 OK"
2026-06-28 17:13:29,167 | INFO | HTTP Request: POST https://litellm.tokengate.ru/v1/chat/completions "HTTP/1.1 200 OK"
2026-06-28 17:13:29,412 | INFO | HTTP Request: POST https://litellm.tokengate.ru/v1/chat/completions "HTTP/1.1 200 OK"
Generating Q&A:  26%|██▌       | 52/200 [00:15<00:24,  6.16it/s]2026-06-28 17:13:29,437 | INFO | HTTP Request: POST https://litellm.tokengate.ru/v1/chat/completions "HTTP/1.1 429 Too Many Requests"
2026-06-28 17:13:29,438 | INFO | Retrying request to /chat/completions in 0.402137 seconds
2026-06-28 17:13:29,458 | INFO | HTTP Request: POST https://litellm.tokengate.ru/v1/chat/completions "HTTP/1.1 429 Too Many Requests"
2026-06-28 17:13:29,458 | INFO | Retrying request to /chat/completions in 0.429357 seconds
2026-06-28 17:13:29,703 | INFO | HTTP Request: POST https://litellm.tokengate.ru/v1/chat/completions "HTTP/1.1 200 OK"
Generating Q&A:  26%|██▋       | 53/200 [00:15<00:27,  5.36it/s]2026-06-28 17:13:30,147 | INFO | HTTP Request: POST https://litellm.tokengate.ru/v1/chat/completions "HTTP/1.1 429 Too Many Requests"
2026-06-28 17:13:30,148 | INFO | Retrying request to /chat/completions in 0.759907 seconds
2026-06-28 17:13:30,171 | INFO | HTTP Request: POST https://litellm.tokengate.ru/v1/chat/completions "HTTP/1.1 429 Too Many Requests"
2026-06-28 17:13:30,171 | INFO | Retrying request to /chat/completions in 0.849518 seconds
2026-06-28 17:13:30,192 | INFO | HTTP Request: POST https://litellm.tokengate.ru/v1/chat/completions "HTTP/1.1 200 OK"
2026-06-28 17:13:30,193 | INFO | HTTP Request: POST https://litellm.tokengate.ru/v1/chat/completions "HTTP/1.1 200 OK"
2026-06-28 17:13:30,196 | INFO | HTTP Request: POST https://litellm.tokengate.ru/v1/chat/completions "HTTP/1.1 200 OK"
Generating Q&A:  27%|██▋       | 54/200 [00:15<00:36,  3.99it/s]2026-06-28 17:13:30,453 | INFO | HTTP Request: POST https://litellm.tokengate.ru/v1/chat/completions "HTTP/1.1 200 OK"
Generating Q&A:  28%|██▊       | 57/200 [00:16<00:24,  5.79it/s]2026-06-28 17:13:30,596 | INFO | HTTP Request: POST https://litellm.tokengate.ru/v1/chat/completions "HTTP/1.1 200 OK"
Generating Q&A:  29%|██▉       | 58/200 [00:16<00:23,  5.98it/s]2026-06-28 17:13:30,905 | INFO | HTTP Request: POST https://litellm.tokengate.ru/v1/chat/completions "HTTP/1.1 200 OK"
Generating Q&A:  30%|██▉       | 59/200 [00:16<00:27,  5.08it/s]2026-06-28 17:13:31,133 | INFO | HTTP Request: POST https://litellm.tokengate.ru/v1/chat/completions "HTTP/1.1 200 OK"
Generating Q&A:  30%|███       | 60/200 [00:16<00:28,  4.91it/s]2026-06-28 17:13:31,218 | INFO | HTTP Request: POST https://litellm.tokengate.ru/v1/chat/completions "HTTP/1.1 200 OK"
2026-06-28 17:13:31,559 | INFO | HTTP Request: POST https://litellm.tokengate.ru/v1/chat/completions "HTTP/1.1 200 OK"
Generating Q&A:  31%|███       | 62/200 [00:17<00:28,  4.82it/s]2026-06-28 17:13:31,611 | INFO | HTTP Request: POST https://litellm.tokengate.ru/v1/chat/completions "HTTP/1.1 200 OK"
2026-06-28 17:13:31,736 | INFO | HTTP Request: POST https://litellm.tokengate.ru/v1/chat/completions "HTTP/1.1 429 Too Many Requests"
2026-06-28 17:13:31,736 | INFO | Retrying request to /chat/completions in 0.441184 seconds
2026-06-28 17:13:32,538 | INFO | HTTP Request: POST https://litellm.tokengate.ru/v1/chat/completions "HTTP/1.1 200 OK"
Generating Q&A:  32%|███▏      | 64/200 [00:18<00:42,  3.23it/s]2026-06-28 17:13:32,603 | INFO | HTTP Request: POST https://litellm.tokengate.ru/v1/chat/completions "HTTP/1.1 200 OK"
2026-06-28 17:13:32,689 | INFO | HTTP Request: POST https://litellm.tokengate.ru/v1/chat/completions "HTTP/1.1 200 OK"
Generating Q&A:  33%|███▎      | 66/200 [00:18<00:30,  4.35it/s]2026-06-28 17:13:32,731 | INFO | HTTP Request: POST https://litellm.tokengate.ru/v1/chat/completions "HTTP/1.1 200 OK"
2026-06-28 17:13:32,927 | INFO | HTTP Request: POST https://litellm.tokengate.ru/v1/chat/completions "HTTP/1.1 429 Too Many Requests"
2026-06-28 17:13:32,928 | INFO | Retrying request to /chat/completions in 0.463711 seconds
2026-06-28 17:13:33,181 | INFO | HTTP Request: POST https://litellm.tokengate.ru/v1/chat/completions "HTTP/1.1 200 OK"
Generating Q&A:  34%|███▍      | 68/200 [00:18<00:31,  4.26it/s]2026-06-28 17:13:33,203 | INFO | HTTP Request: POST https://litellm.tokengate.ru/v1/chat/completions "HTTP/1.1 200 OK"
2026-06-28 17:13:33,639 | INFO | HTTP Request: POST https://litellm.tokengate.ru/v1/chat/completions "HTTP/1.1 200 OK"
Generating Q&A:  35%|███▌      | 70/200 [00:19<00:30,  4.29it/s]2026-06-28 17:13:33,828 | INFO | HTTP Request: POST https://litellm.tokengate.ru/v1/chat/completions "HTTP/1.1 200 OK"
Generating Q&A:  36%|███▌      | 71/200 [00:19<00:29,  4.44it/s]2026-06-28 17:13:33,841 | INFO | HTTP Request: POST https://litellm.tokengate.ru/v1/chat/completions "HTTP/1.1 200 OK"
2026-06-28 17:13:34,431 | INFO | HTTP Request: POST https://litellm.tokengate.ru/v1/chat/completions "HTTP/1.1 200 OK"
Generating Q&A:  36%|███▋      | 73/200 [00:20<00:31,  3.97it/s]2026-06-28 17:13:34,476 | INFO | HTTP Request: POST https://litellm.tokengate.ru/v1/chat/completions "HTTP/1.1 200 OK"
2026-06-28 17:13:34,544 | INFO | HTTP Request: POST https://litellm.tokengate.ru/v1/chat/completions "HTTP/1.1 200 OK"
Generating Q&A:  38%|███▊      | 75/200 [00:20<00:23,  5.35it/s]2026-06-28 17:13:34,723 | INFO | HTTP Request: POST https://litellm.tokengate.ru/v1/chat/completions "HTTP/1.1 429 Too Many Requests"
2026-06-28 17:13:34,724 | INFO | Retrying request to /chat/completions in 0.466102 seconds
2026-06-28 17:13:34,847 | INFO | HTTP Request: POST https://litellm.tokengate.ru/v1/chat/completions "HTTP/1.1 200 OK"
Generating Q&A:  38%|███▊      | 76/200 [00:20<00:25,  4.78it/s]2026-06-28 17:13:35,004 | INFO | HTTP Request: POST https://litellm.tokengate.ru/v1/chat/completions "HTTP/1.1 200 OK"
Generating Q&A:  38%|███▊      | 77/200 [00:20<00:24,  5.05it/s]2026-06-28 17:13:35,047 | INFO | HTTP Request: POST https://litellm.tokengate.ru/v1/chat/completions "HTTP/1.1 200 OK"
2026-06-28 17:13:35,051 | INFO | HTTP Request: POST https://litellm.tokengate.ru/v1/chat/completions "HTTP/1.1 200 OK"
2026-06-28 17:13:35,206 | INFO | HTTP Request: POST https://litellm.tokengate.ru/v1/chat/completions "HTTP/1.1 200 OK"
Generating Q&A:  40%|████      | 80/200 [00:20<00:16,  7.39it/s]2026-06-28 17:13:35,358 | INFO | HTTP Request: POST https://litellm.tokengate.ru/v1/chat/completions "HTTP/1.1 429 Too Many Requests"
2026-06-28 17:13:35,358 | INFO | Retrying request to /chat/completions in 0.857606 seconds
2026-06-28 17:13:35,433 | INFO | HTTP Request: POST https://litellm.tokengate.ru/v1/chat/completions "HTTP/1.1 200 OK"
Generating Q&A:  40%|████      | 81/200 [00:21<00:18,  6.57it/s]2026-06-28 17:13:35,579 | INFO | HTTP Request: POST https://litellm.tokengate.ru/v1/chat/completions "HTTP/1.1 200 OK"
Generating Q&A:  41%|████      | 82/200 [00:21<00:17,  6.62it/s]2026-06-28 17:13:36,273 | INFO | HTTP Request: POST https://litellm.tokengate.ru/v1/chat/completions "HTTP/1.1 200 OK"
Generating Q&A:  42%|████▏     | 83/200 [00:21<00:32,  3.62it/s]2026-06-28 17:13:36,353 | INFO | HTTP Request: POST https://litellm.tokengate.ru/v1/chat/completions "HTTP/1.1 200 OK"
2026-06-28 17:13:36,387 | INFO | HTTP Request: POST https://litellm.tokengate.ru/v1/chat/completions "HTTP/1.1 200 OK"
Generating Q&A:  42%|████▎     | 85/200 [00:22<00:21,  5.29it/s]2026-06-28 17:13:36,400 | INFO | HTTP Request: POST https://litellm.tokengate.ru/v1/chat/completions "HTTP/1.1 429 Too Many Requests"

Generated: 199 Q&A pairs

,question_id,source_note_id,note_text,note_domain,note_style,question,reference_answer,question_type,key_concepts,ground_truth_zettel_ids,n_gt_zettels,generated_at,model_name,№
0,Q-0A1D247E,33ba4155-d599-4f78-b9f2-f18f10c6bd4a,Звонок с Андреем и Michael из DHL по поставкам...,операционная деятельность,записи после звонка,"Напомни, какой именно лимит на экспресс-достав...",Решили временно поднять лимит на экспресс до 1...,factual,"[""лимит на экспресс"", ""1,8 млн рублей"", ""проек...","[""fa44b3b5-f93c-40ee-bdee-870f0f1a08a1""]",1,2026-06-28T17:13:18.289649,openai/gpt-5.1,1
1,Q-FB4EB54F,142f182e-072c-4364-9058-c71303b5a194,Только что посмотрел с Олей и Mark дашборд в T...,аналитика и метрики,голосовая заметка,"Напомни, какую оценку по потере MRR называла К...",Катя оценивает потенциальное влияние на MRR ка...,factual,"[""Катя"", ""падение конверсии trial→оплата у Сбе...","[""cd4790f7-8b58-4c57-bfc3-13b1d2d3a464"", ""ec29...",5,2026-06-28T17:13:18.299467,openai/gpt-5.1,2
2,Q-8F323939,9c5f97c0-f0f3-4cc0-b272-5ddf4bab53b4,"Думаю по людям в команде Phoenix, нагрузка уже...",управление персоналом,рабочие мысли,"Напомни, к какому сроку мы рисковали сдвинуть ...",Если до 15 июля не закрыть двух backend-разраб...,factual,"[""проект Vega для MTS"", ""срок до 15 июля"", ""дв...",[],0,2026-06-28T17:13:18.446104,openai/gpt-5.1,3

In [11]:
df_qa.to_excel(OUTPUT_PATH, index=False)
print(f'Saved to {OUTPUT_PATH}')

print('\n=== Dataset Statistics ===')
print(f'Total Q&A pairs:              {len(df_qa)}')
print(f'With GT zettels:              {(df_qa["n_gt_zettels"] > 0).sum()}')
print(f'Avg GT zettels per question:  {df_qa["n_gt_zettels"].mean():.2f}')
print(f'Questions with 0 GT zettels:  {(df_qa["n_gt_zettels"] == 0).sum()}')

print('\nQuestion type distribution:')
print(df_qa['question_type'].value_counts())

# Предупреждение: вопросы без GT zettel-ов будут пропущены в retrieval eval
zero_gt = (df_qa['n_gt_zettels'] == 0).sum()
if zero_gt > 0:
    print(f'\n⚠️  {zero_gt} questions have 0 GT zettels (threshold={GT_SIM_THRESHOLD}).')
    print('Consider lowering GT_SIM_THRESHOLD if too many are missing.')

Saved to synthetic_datasets/rag_qa_dataset.xlsx

=== Dataset Statistics ===
Total Q&A pairs:              199
With GT zettels:              131
Avg GT zettels per question:  2.43
Questions with 0 GT zettels:  68

Question type distribution:
question_type
factual         154
decision         32
action_items      6
risk              4
detail            2
summary           1
Name: count, dtype: int64

⚠️  68 questions have 0 GT zettels (threshold=0.6).
Consider lowering GT_SIM_THRESHOLD if too many are missing.

In [12]:
# Просмотр нескольких примеров
for i, row in df_qa.head(2).iterrows():
    print(f"{'='*80}")
    print(f"[{row['question_type'].upper()}] {row['question']}")
    print(f"\nAnswer: {row['reference_answer'][:300]}...")
    print(f"GT zettels ({row['n_gt_zettels']}): {row['ground_truth_zettel_ids'][:100]}...")

================================================================================
[FACTUAL] Напомни, какой именно лимит на экспресс-доставку мы тогда решили временно поднять в рамках проекта «Север» для клиента ВекторФарм из‑за задержки партии в Риге?

Answer: Решили временно поднять лимит на экспресс до 1,8 млн рублей....
GT zettels (1): ["fa44b3b5-f93c-40ee-bdee-870f0f1a08a1"]...
================================================================================
[FACTUAL] Напомни, какую оценку по потере MRR называла Катя из‑за падения конверсии trial→оплата у СберМаркета в проекте Orion, если тренд не развернуть?

Answer: Катя оценивает потенциальное влияние на MRR как минус 4,5 млн рублей, если тренд падения конверсии не развернуть....
GT zettels (5): ["cd4790f7-8b58-4c57-bfc3-13b1d2d3a464", "ec29692a-3b9b-46af-bc64-7b49e192bdfa", "3a47e2ef-cffb-4835...